
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true 
canonifyurls = false
theme = "hugo-tufte"
title = "Lisa's Notebook"

[permalinks]
    post = "/:year/:month/:day/:title/"


[taxonomies]
  category = "categories" 
  refs = "refs"
  series = "series"
  tag = "tags"

[params]
  subtitle = "Writing Exercises by Lisa McNulty."
  copyrightHolder = "Lisa McNulty"
  showPoweredBy = false

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = 10 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = 20 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Tags"
  pre = "<i class='fa fa-tags fa-lg'></i> "
  weight = 30 
  identifier = "tags"
  url = "/tags"
[[menu.nav]]
  name = "Writers"
  pre = "<i class='fa fa-tags fa-lg'></i> "
  weight = 31 
  identifier = "refs"
  url = "/refs"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------

