---
title: The Article-A-Day Challenge 
author: "Lisa McNulty"  
date: "2020-07-01"
twitterImg: papers.jpg
description: "intimidating as hell, and therefore it’s a very good idea"
---


A recommendation/challenge has emerged from Dr Olivia Rissland on Twitter to read one academic article a day and keep a record of it

```{r echo=FALSE}
blogdown::shortcode('tweet', '1273329913626411008')
```  

This is so far above my current density for reading academic articles that it is intimidating as hell, and therefore it’s a very good idea for me to try it. The beginning of a new month seems like a good time to start this. The initial rules shall be: 

*   It doesn’t have to be in my field, though most of them will be, 
*   Chapters from academic textbooks count as ‘articles’, 
*   Re-reads of materials I want to refamilarize myself with are are permitted, but I can’t count the same paper twice in the challenge itself,
*   I don’t have to write a proper review of them, just the title and an optional line on the topic,
*   Articles to be put into RefWorks as I go. 

I will initially try to do this as a daily practice, but it might become undoable at weekends. I’ll experiment and see. If so, possibly I can double up on a couple of weekdays to balance it out. If I manage to read (the equivalent of) an article daily, I will have read 184 articles by the end of the year, which seems like a good goal. But the initial goal is 31 articles by 1st August; so expect a post on the 1st August on how I got on. 

**Today’s article:** Goldberg, S. (2013) _Epistemic dependence in testimonial belief, in the classroom and beyond_. Journal of Philosophy of Education. 47(2) pp.168-186. Criticises the Cartesian conception of intellectual autonomy, arguing that not only children but adults remain epistemically dependent on others throughout their lives. 
