---
title:  "Locke’s Conduct of the Understanding: A Translation Section One"
author: "Lisa McNulty"  
date: "2020-09-19"
series: 
   - "Locke’s Conduct of the Understanding: A Translation."
refs:
  - "John Locke"
twitterImg: locke conduct.jpeg
description: "seventeenth century self-help"
output:
  html_document:
    code_folding: hide

---


I’ve got a new blog project which should provide me with some shortish, simpleish writing exercises for some time to come. I intend to write a translation of _Locke’s Conduct of the Understanding_. Now obviously Locke wrote in English, but in seventeenth century English, which I am given to understand is not as easy a read for most people as it is for me. So I’m going to go through section by section and re-write it into modern English. For anyone who wants to read the original in full, it is available [here](https://www.ebooksread.com/authors-eng/john-locke/lockes-conduct-of-the-understanding-kco.shtml).

**Section I. Introduction**

<details>
  <summary>Original Text</summary>

The last resort a man has recourse to in the conduct of himself is his understanding; for though we distinguish the faculties of the mind, and give supreme command to the will as an agent, yet the truth is, the man who is the agent determines himself to this or that voluntary action upon some precedent knowledge, or appearance of knowledge, in the understanding.

</details>


Our actions depend upon our understanding of the world. We act in accordance with our will (what we want to achieve), but we choose our course of action based on what we know (or what we think we know). 

<details>
  <summary>Original Text</summary>
  
No man ever sets himself about any thing but upon some view or other which serves him for a reason for what he does: and whatsoever faculties he employs, the understanding, with such light as it has, well or ill informed, constantly leads; and by that light, true or false, all his operative powers are directed. The will itself, however absolute and uncontrollable soever it may be thought, never fails in its obedience to the dictates of the understanding. 

</details>

No one does anything without (thinking that they have) a good reason. Therefore, your _abilities to act_ (sensibly) are dependent on your knowledge and understanding of how the world works. We might think that our ‘will to act’ is in control of things, but actually that ‘will to act’ is answerable to our understanding (accurate or inaccurate) of what the results of those actions are likely to be. 

{{% marginnote %}}    
Locke is arguing very hard here against the idea that there is an inherently Rational Will guiding our actions based on some kind of _innate_ knowledge  of the world. This is liable to be lost on the modern reader because it’s a wildly unpopular idea by now anyway.  
{{% /marginnote %}}

<details>
  <summary>Original Text</summary>

Temples have their sacred images, and we see what influence they have always had over a great part of mankind. But in truth the ideas and images in men’s minds are the invisible powers which constantly govern them, and to these they all universally pay a ready submission. It is therefore of the highest concernment that great care should be taken of the understanding, to conduct it right in the search of knowledge and in the judgments it makes. t of the mind and understanding should be introduced.' Necessario reqiii- ritur ut melior et pcrfcclior mentis et intdkctus humani usus et adoperatio introducalur,  

</details>

We see how religious images influence people, and how they submit to them. We don’t, however, notice how we submit to the images and unquestioned ideas in our own minds. Our beliefs and actions are affected by these to a far greater degree than we realise. It is of the highest concern that we become aware of how we think, in order that we can seek knowledge more effectively and make better judgments. 

{{% marginnote %}}    
 ‘Judgment’ is ambiguous here. It can mean both ‘judgment about what the truth is, which falls short of certainty as to what the truth is’ and ‘making a decision about what to do’. {{% /marginnote %}}

<details>
  <summary>Original Text</summary>

The logic now in use has so long possessed the chair as the only art taught in schools for the direction of the mind in the study of the arts and sciences, that it would perhaps be thought an affectation of novelty to suspect that the rules which have served the learned world these two or three thousand years, and which, without any complaint of defects, the learned have rested in, are not sufficient to guide the understanding. And I should not doubt but that this attempt would be censured as vanity or presumption, did not the great Lord Verulam’s authority justify it; who, not servilely thinking learning could not be advanced beyond what it was, because it was, but enlarged his mind to what it could be. 

</details>

The usual approach to ‘studying the way we think’ is, and has been for two or three thousand years, the study of logic in schools and universities. Educated people have relied on this training to guide their understanding of the world and have considered it sufficient. They might be inclined to think me vain and presumptuous for questioning this approach, were it not for the fact that the respected Francis Bacon (Lord Verulam) has done so already. Not being of a servile temperament, he was able to look beyond how education is actually practiced to how it might be improved. 

<details>
  <summary>Original Text</summary>

In his preface to the Novum Organum, concerning logic he pronounces thus: _Qui summas Dialecticae partes tribuerunt atque inde fidissima Scientiis praesidia comparari putarunt verissime et optime viderunt intellectum humanum sibi permissum merito suspectum esse debere. Verum infirmior omnino est malo medicina; nec ipsa mali expers. Si quidem Dialectica, quae recepta est, licet ad civilia et  artes, quae in sermone et opinione positae sunt, rectissime adhibeatur; naturae tamen subtilitatem longo intervallo non attingit, et prensando, quod non capit, ad errores potius stabiliendos et quasi figendos, quam ad viam veritati aperiendam valuit._

	‘They’, said he, ‘who attributed so much to logic, perceived very well and truly, that it was not safe to trust the understanding to itself, without the guard of any rules. But the remedy reached not the evil; but became part of it: for the logic which took place, though it might do well enough for civil affairs and the arts which consisted in talk and opinion, yet comes very far short in subtilty in the real performances of nature, and catching at what it cannot reach, has served to confirm and establish errors, rather than to open a way to truth.’ And therefore a little after that he says, ‘That it is absolutely necessary that a better and perfecter use and employment of the mind and understanding should be introduced.’ _Necessario requiritur ut melior at perfectior mentis et intellectus humani usus et adoperatio introducatur.  _

</details>

Those who study logic do so because they recognise that the understanding cannot manage itself: there are rules for thinking well. Unfortunately, the rules for thinking well about abstract intellectual subjects do not work as well for all areas of thinking, notably thinking about 
{{% marginnote %}}    It’s interesting to note that Locke both uses the original Latin and translates it himself into English. He doesn’t assume that his readers understand Latin.  {{% /marginnote %}} the natural world. If the rules of logic taught in universities are your only conception of what thinking well looks like, then you are actually likely to make_ more_ errors in your broader studies than someone who never studied logic in the first place, and to be more certain that your errors are the truth. We must therefore find a better way of educating students in how to think well than merely teaching them logic. 



