---
title: "Beauty and Identity"
author: "Lisa McNulty"
date: "2020-05-01"
categories: 
    - "lockdown"
    - "Disney"
    - "Agnetology"
---

Lockdown has me watching far too much classic Disney with my daughter. This has me thinking a lot about beauty and identity. Predictably, the movies depict a strong connection between ‘beauty’ and ‘goodness’. The leading women are, of course, very beautiful, with that beauty clearly presented as a physical manifestation of their innate goodness. Villains are generally identifiable by their ugliness. Plainness, meanwhile, is dullness; a sign that you aren’t really part of the story at all. 

However, there is an exception to the beautiful = good rule. If a character recognises their own beauty, identifies themselves with it, and seeks to preserve it, then they are certainly a villain. The Queen in Snow White knows that she is beautiful, demands affirmation that she remains beautiful, and turns violent to ensure that she continues to be perceived as the most beautiful in the land. The witch in ‘Tangled’ is beautiful because she has taken measures to preserve her beauty beyond its natural lifespan, by exploiting the ‘genuinely’ beautiful Rapunzel. The male version of this trope is Gaston in Beauty and the Beast, and his awareness of his own attractiveness is presented as part of his broader arrogance and therefore unworthiness.  The stepmother in Cinderella is a slightly unusual manifestation of the trope in that whilst she is not actually beautiful, she is poised and elegant and refined, and seeks (persistently and unsuccessfully) to educate her daughters to emulate those qualities in order to improve their attractiveness. Beauty in this instance is artifice, performed in order to achieve one’s ambitions. 

So beauty reflects goodness only when no effort is made to make oneself beautiful. It is not exactly necessary, as in the One Direction song, to not know that you are beautiful, but it is at least necessary that you should never mention your beauty, indicate that you find it important, or openly take steps to preserve or increase it. The extent to which Disney influences the public consciousness on this and the extent to which it merely reflects it is unclear, and I don’t intend to unpack this question here. But certainly to see beauty praised whilst the necessary efforts behind it are mocked is a deeply discomforting double bind. 

There are broadly four options for responding to this general culture:  

1. *Be beautiful without effort.* 
Insofar as this is an option at all, it is extremely time-limited. There is a reason so many Disney princesses are sixteen. 

2. *Put in the effort but conceal the fact that this is happening.* 
This is the way of shaving commercials in which women have no hair to shave; of ‘natural look’ makeup and magic underwear and a certain amount of self-loathing. 

3. *Put in the effort and don’t conceal the fact that this is happening.*
This is beauty as a deliberately cultivated performance, as ritual. It tends to be bolder, brighter, more dramatic, more individual. It might be, but is not necessarily, queer (as so many Disney villains are). 

4. *Opt out of the story altogether. Refuse to engage.*
Don’t perform beauty at all, or do the bare minimum to avoid attention. This might be political (this is bullshit) or nerd (bodies are boring, I am a mind) or both. 

For much of my life, I have taken Option 4, as I have considered it an appropriate rebellion from an awful lot of bullshit effort. I am also a nerd - or rather an academic - and therefore have been deeply influenced by a subculture which encourages me to define myself by my intellect, as opposed to my body. This is, in all honesty, a quick and easy way to feel superior to the mainstream.

However, within Option 4, I have taken the ‘bare minimum’ subcategory. The ‘don’t perform beauty at all’ option carries too high a social price, especially for women, and doesn’t actually appeal to me anyway (I dislike leaving my legs unshaved, for example.) The trouble is, the ‘bare minimum effort’ baseline gradually increases with age, and starts to blur imperceptibly into Option 2. For example, at some point in my thirties, not wearing make-up to certain events became itself a statement, one which I had no desire to spend spoons on making. So I wear it, occasionally and therefore really quite badly. 

One path from here is to reaffirm the refusal to engage. But I no longer connect to the ‘nerd’ reason to opt out. I am increasingly aware that bodies *aren’t* boring, and I am *not* (just) a mind. In fact the more aware I am of my body, the better my mind seems to work. It is deeply frustrating to me that I was not aware of this sooner. Performing beauty, done right, could in fact be a means to connect my mind and my body *better*. The political reason, though, remains. To a large degree, the obligation to perform beauty is indeed bullshit. However, the more significant bullshit is surely the pretence that the performance isn’t going on. 

Increasingly, then, Option 3 appeals. This requires acknowledging that yes, I do value beauty, and I am willing to put in a certain amount of effort to achieve it. It means engaging, but doing so deliberately, boldly, and without concealing the fact. It means performing beauty as a villain does. Perhaps it’s the better rebellion. 
