---
title: How Not To Think Like Sherlock Holmes
slug: Sherlock
author: "Lisa McNulty"  
---

If you've enjoyed my posts on [How Not To Think Like Sherlock Holmes](/series/how-not-to-think-like-sherlock-holmes/) you would probably also enjoy my online course, also called "How Not To Think Like Sherlock Holmes"


Come and discover the reasoning skills of the Master of Deduction. Just how does Sherlock Holmes come to his conclusions? How does he convince Scotland Yard that he is right? And is it wise of him to forget that the earth goes around the sun?

An exploration of critical thinking and epistemology through the magnifying lens of the great detective, intended to have you musing and amused.

## July 30th Week One: Master of Deduction?: 
Are Sherlock Holmes's arguments deductive? Deductive validity, inductive force, and alternative explanations.

## August 6th Week Two: Why believe Holmes?: 
An examination of epistemic privilege, and what it means to argue well.

## August 13th Week Three: 
Eliminating the Impossible: Can we? And if we do, is whatever remains (however improbable) necessarily the truth?

## August 20th Week Four: 
The Solitary Genius: How the world's only consulting detective thinks for (and by) himself; and why he shouldn't.

## August 27th Week Five: 
Stocking the Brain-Attic: On wilful ignorance and not knowing what you don't know.

Brought to you by The Philosophy Foundation (and me!), this 5 week course is £50 in total and each evening runs from 7pm-8.30pm.



# You can buy tickets [here](https://www.eventbrite.co.uk/e/how-not-to-think-like-sherlock-holmes-tickets-112121807344)