---
title: What is this Blog For, Again? 
author: "Lisa McNulty"  
date: "2020-07-16"  
series:  
tags:
- "Self-indulgence"
refs:  
- "DAvid MacIver"
twitterImg: draft.jpg
description: "I think I need another blog..."

---


Forgive the self-indulgence of this entry. I am genuinely trying to work out the answer to this question. 

I, like many, adopted this notebook blog inspired by [David MacIver](https://notebook.drmaciver.com/), who makes a convincing case for the value of writing daily. This blog was initially intended to be a daily blog, and for the first month, full of enthusiasm for a new project, it almost was. The intensity has dialled down a bit since. I’ve consciously made a choice *not* to write daily, but instead ‘regularly’; and I’ve left ‘regularly’ fairly vague. This takes a bit of the pressure off and allows me to be what I think of as productively [inconsistent](/2020/05/04/consistency-is-the-enemy/), so that if I need to give my full focus to something else and skip out on writing here, that’s OK. 

I’ve noticed, though, that many people who have a notebook blog already had another, more ‘official’ blog, which they use to publish their more polished articles. They are using their notebook blogs to experiment and improve their writing habits, and picking out their best pieces to move over to another, main site.

In my case, this is my first blog, and all my writing is in one place. The result is that I’m trying to both showcase my best writing, and carve out a low-pressure space to _just write_, in that same place. 

I kind of like the intellectual honesty of this in principle, but I’ve found that the standard set by my more polished articles on this site has gradually become an inhibiting factor against writing at all on days where my efforts are likely to be less than stellar. I’ve used drabbles, which have helped with this to some degree, as they are reasonably polished but also very short. However, they aren’t enough to solve the problem. My blog is trying to perform two very different functions at once, and they pull against each other.

So the options are: 



*   **Lean into this being a showcase space. **If I take this option, I would be doing the ‘rough drafts’ privately and publishing on the notebook once a week or so. 
*   **Lean into this being a ‘rough draft’ space.** In that case, I give myself permission to write... I don’t want to say _badly_, but let's face it, _badly_, in order to write often, and then cherry-pick and polish the best to put somewhere else. 

It’s taken quite a shift in mindset to write publicly on a regular basis, and so I think the first option would be a backwards move. The upshot is:  I think I need another blog, one which is just for the edited highlights. I’ll set this up over the next couple of weeks and announce it here when I have. 

