---
title: "On not bullshitting about ‘On Bullshit’ "
slug: "OnBullshit2"
author: "Lisa McNulty"
date: "2020-07-12"
series:
tags: 
- "Bullshit"
refs:
- "Harry G Frankfurt"
- "Ivo Weaver"
twitterImg: bull.jpg
description: "Hopefully I haven’t contributed to the pile today."
---



Ivo Wever (@Confusionist) offered the following objection to yesterday’s post: 

{{% tweet 1281314680414314496 %}}

> Could Krauss be ‘sincere, inconsistent and wrong’ instead of ‘a bullshitter’? He may not have realized he had given insufficient thought to the matter until strongly challenged? If motivation doesn’t matter, aren’t we all bullshitters at times?

I thought this deserved a substantial reply, which is up on Twitter but will double as my post for today. Here it is: 

OK. So. Strap in, this is gonna get a bit meta.

Firstly, yes, it’s possible. It’s not the impression I get, but it’s possible, and it’s a possibility that I didn’t acknowledge in the post.

The temptation to retcon an excellent reason for not having included it in the original post, one more respectable than ‘I was more interested in the other things I was writing about’, is palpable. I’m pretty sure I could think of a few plausible ones. I’m also pretty sure that I would then quite rapidly forget that I didn’t think of them in the first place.  

I don’t think I’m alone in this. I suspect that this temptation, and forgetfulness, is entirely normal, that it arises from a desire to feel intellectually capable, and that such from the inside, such a desire can be damned difficult to tell apart from the desire to figure out the truth.   

In other words, I was motivated to bullshit here.

So in answer to ‘aren’t we all bullshitters at times’ is hell yes, and we are in fact more vulnerable to bullshitting than we are to lying, because we generally know when we are lying, whereas it takes careful attention and a practiced intellectual honesty to try to ensure that we aren’t bullshitting.

Frankfurt’s opening line in ‘On Bullshit’ is “One of the most salient features of our culture is that there is so much bullshit. Everyone knows this. Each of us contributes his share.” Hopefully I haven’t contributed to the pile today. 
