---
title: "Justified True Belief in Education"
author: "Lisa McNulty"
date: "2020-06-01"
series:
tags: 
- "Epistemology"
refs:
- "Edmund Gettier"


---

I find the thought of doing epistemology without talking about education faintly bizarre. Theory of knowledge, even at its most abstract, seems so deeply connected to theories of learning that it surprises me how distinct the fields are in practice. For this piece I’m going to play around with the traditional, tripartite definition of knowledge just to see how each of the three elements maps onto educational practices. 

{{% marginnote %}} Note, I am well aware of the limitations of the tripartite definition of knowledge, and not only because of [Gettier](https://en.wikipedia.org/wiki/Gettier_problem) but it’s not *not* useful and it’s fun to play with it here. {{% /marginnote %}} 

So the tripartite definition of knowledge is: in order for something to count as a piece of knowledge, it has to be a *justified true belief*. That is, the statement must be true, you must believe it to be true, and you must have a justification for that belief.  {{% marginnote %}}One major limitation of the tripartite definition is that it only addresses propositional knowledge. Experiential knowledge and know-how don’t fit.{{% /marginnote %}} The fact that it is true is not in itself a justification. You have to have a good reason to believe it; otherwise it’s just a lucky guess, and we don’t want to rely on lucky guesses.   

So wanting children to know things can be framed as wanting them to have justified true beliefs.

Let’s start with the idea of ‘justification’. What counts as a child being justified in believing something taught to them in the classroom? I’m thinking of something like historical facts, or facts about the solar system, something necessarily outside of their direct physical experience. Is it sufficient to say that they are justified in believing it because the teacher says so?

At the very least, this is a necessary stage. They can’t do independent study at this point, they are not in a strong position to double-check the teacher, and it seems inappropriate to say that they therefore *can’t gain knowledge* from listening to the teacher. But we don’t want this comparative passivity to be a permanent situation. Even though they are not capable of providing a more independent justification for their beliefs right now, they can be set on a path which leads to them being able to do so as adults. Our long term intention for them is that they will not simply, passively receive the beliefs they are presented with, even if those beliefs happen to be true. There are things we can do even in early education which can steer them in this direction. For example, in teaching science, we not only want to teach scientific facts, but also something about how scientific beliefs are justified: not just what scientists believe, but why they believe those things. 

What about ‘truth’, then? It seems an obvious goal that teachers should be telling children the truth. However, suppose that a teacher is talking with their class of primary school students about the solar system, and tells them that the sun is made of burning gas. This is untrue: the sun is made of plasma, not gas, and is undergoing a process of nuclear fusion, which is not the same as combustion, so it’s not burning. The children are being taught something wrong. 

However, even assuming that the teacher knows the more accurate scientific account, it seems wildly uncharitable to say that they are lying to the children. The goal is not to deceive. Rather, the child’s understanding of the world has an existing structure, and the teacher is attempting to fit new information into that structure. 

The children know what ‘burning’, or ‘fire’, is, because they have seen a candle flame (or if they haven’t, it’s easy to show them). They know what gas is, because they know what air and wind are. They may know that there are different kinds of gas, if they have seen a floating helium balloon (and if not, it is easy to show them). By describing the sun as a ball of burning gas, the teacher is able to map that concept onto the child’s existing experiences, and the child ends up with a better insight into what the sun is like than they would have had if the teacher had tried to introduce the concepts of plasma and fusion at this point. The lie works better than the truth.

So, we may deliberately introduce false information as a means to improve a child’s understanding of the world. Unfortunately we may also do the reverse: make use of accurate information which permanently skews their understanding of the world. 

The history curriculum in England is (presumably) broadly accurate. It isn’t giving false information about historical events (not deliberately, at any rate).  However, there is also the matter of which historical events we choose to educate our children about. One sharp contrast we might see here is that English children do not tend to be taught about how the English behaved in Scotland, whereas Scottish children most certainly are. We might also note the distinct absence of any exploration of colonialism within our history curriculum. It is only half a joke to say that we skip straight from the Tudors to the Second World War. The focus gives a very particular impression of England and its role in history, and not one which many other countries would recognise. 

In short, the truths taught in history are far more deceitful than the lies taught in science.

The third element is belief. By this I don’t just mean believing the claim, but believing the teacher. Trust is a foundation stone for knowledge. Whether or not children believe their teachers will depend on a couple of factors outside of the teacher’s control, and one that is in their control.

*Firstly*, if there are untrustworthy adults in other areas of their lives, children are unlikely to trust their teachers either. There is epistemic damage done here (on top of everything else). All a teacher can do is continue to be trustworthy and hope that the evidence of them being trustworthy keeps building up until eventually those children trust them.

*Secondly*, if there are trustworthy adults in other areas of their lives, and those adults disagree with the teacher, the child has to choose who to believe. One example of this happened to a friend of mine. She was explaining the water cycle to a primary school class when a child interrupted to say ‘That's not how clouds work. Rain clouds are God crying. My mum says so.’ Given the choice between trusting a teacher and trusting a parent, young children will generally choose the latter, and teachers have to be careful about how they handle situations like these. Simply dismissing a parent’s testimony, however silly it may be, is a poor tactic. 

*Thirdly*, and this is the one most under the teacher’s control: the teacher must not conceal ignorance, and must not deny mistakes. You do not have to be infallible in order to be a reliable source of knowledge. If you present yourself as infallible, you will eventually be caught out. Once you are caught out, you will be seen as untrustworthy, and then you cease to be a reliable source of knowledge. 
So some of the most epistemically powerful things a teacher can say are:

* I don’t know the answer to your question. Let’s look it up together. 
* Huh. It seems like I was wrong about that. 

If your ignorance is visible, your knowledge is visible too. Which means that the children will believe you, will be justified in believing you, and you will have an opportunity to ensure that their overall understanding of the world holds true. 