---
title: Philosophy and Therapy
author: "Lisa McNulty"  
date: "2020-07-21"  
series:  
tags:
refs:  
- "Lou Marinoff"
- "Plato"
twitterImg: counselling.jpg
description: "Good philosophy and good therapy are different things requiring different kinds of training."

---


I find the relationship between philosophy and therapy fascinating, problematic, and potentially dangerous. First let’s unpack what the relationship is, and I’ll show you what I mean. 

Firstly, and least controversially in my view, there are qualified therapists who openly use philosophy as part of their toolkit. The most typical example of this is [existentialist psychotherapy](https://www.goodtherapy.org/learn-about-therapy/types/existential-psychotherapy), which draws on existentialist philosophical texts, and frames client’s experiences around ‘existential anxiety’ about freedom and responsibility, death, isolation, and meaning/meaninglessness . My former employer Regents University offers an advanced diploma in existential psychotherapy which has a minimum prerequisite of a MA in psychotherapy and counselling. Essentially in this case we are talking about people who are therapists first and foremost, and use philosophy to be better therapists. I haven’t had any direct experience of this type of therapy and so am not really in a place to say whether it works, but it doesn’t strike me as problematic. This is therapy, which is held to the _standards_ of good therapy, but which happens to borrow from philosophy.

Secondly, we have practical-minded philosophers who feel that philosophy has some therapeutic value in the general sense.  Sometimes this is drawn from the Socratic idea that the ‘unexamined life is not worth living’, or in other words, philosophical reflection is there to improve your overall quality of life, deepen your experiences and help you to make sense of things. It might help you to make moral choices, or epistemically better decisions, or evaluate political institutions better, depending on the area of philosophy you are talking about. This is a general ‘get out of the ivory tower, put philosophy to work, improve lives’ type sentiment that I approve of and share to a great degree. This is philosophy, held to the _standards_ of good philosophy, which happens to have half an eye on therapeutic value. 

I see red flags, however, when philosophers claim _that they are therapists_, or counsellors. For example, the APPA worries me.

The American Philosophical Practitioners Association is headed by Lou Marinoff, whose two most famous books on philosophical counselling are titled respectively _Plato not Prozac!_ and _Therapy for the Sane_.  {{% marginnote %}} I am *really* uncomfortable with the implication that philosophers qua philosophers have any kind of right to question whether or not people should be taking medications, and the implication that conventional therapy is for the ‘insane’ is, just, gah. {{% /marginnote %}} If you have an MA or a Ph.D. in philosophy, you are eligible to undertake their Stage One course in philosophical counselling.This course takes three days. At that point you can complete Stage Two by submitting a questionnaire, plus ten case studies at 7500-10,000 words in total, and become a fully certified philosophical counsellor. 

I have not attended this training. I’ve been tempted to: I suspect it’s very interesting. I would expect that a philosopher learning about therapy would be akin to a therapist learning about philosophy: that is, it might make me a better philosopher, help me to bring philosophy alive and enable me to show people how to connect it to their lives more, but that it _wouldn’t make me a therapist_.  I would actually *love* to philosophise one-on-one with a client, with stuff tailored to their interests, but I would call that a ‘philosophy class’, not a counselling session.

There is definitely a positive relationship to be had between philosophy and therapy, an extent to which good therapy should have a philosophical element and good philosophy should have a therapeutic one. Nonetheless, good philosophy and good therapy are different things requiring different kinds of training.  A therapist inadequately trained in philosophy who fancies themselves a philosopher might potentially be annoying; but a philosopher inadequately trained in therapy who fancies themselves a therapist could be actively dangerous. I am quite happy to prescribe Plato, but whether my students take Prozac is a matter I would sooner leave to those differently qualified to myself. 



