---
title: "June Reading"
author: "Lisa McNulty"
date: "2020-06-30"
series:
  - "Reading"
twitterImg: books.jpg
description: "Things that I read in June"
---



As I said at the end of May, I plan for the last entry of every month to be a record of the reading I’ve done that month. This is my list for June. 


## Novels

  

### The Hollow Lands (Dancers at the End of Time part II), Michael Moorcock

In which Jherek Carnelian continues to be in love with Mrs. Amelia Underwood, travels to nineteenth century London to find her, accidentally becomes a criminal, doesn’t die, and continues with Various Adventures.

  

### The End of all Songs (Dancers at the End of Time part III), Michael Moorcock

In which Jherek Carnelian continues to continue to be in love with Mrs. Amelia Underwood, she makes it back to the End of Time, briefly gains a taste for their hedonistic society (which doesn’t delight Jherek the way he thought it would) before the Twist Happens and the story ends (along with the universe, but that’s by the by.)

  

In other words, I finished [*Dancers at the End of Time*](/2020/06/28/reading-badly-or-goodharts-law/). The trilogy is better thought of as one giant novel, to be honest. It’s an old favourite of mine, and if you like SFF and you like Oscar Wilde, this is great stuff.

  

### Convenience Store Woman, Sayaka Murata

This is a love affair between a (probably autistic) woman and the convenience store she has worked at for eighteen years. It’s about how it isn't normal to be normal when you’re not. It’s short, at 163 pages, and it doesn’t waste a single word. It’s an absolute delight, read it.

  

### Little Fires Everywhere, Celeste Ng

An artist, nomad, and single mother comes to stay in the Pleasant Suburb™ of Shaker Heights, and there are Events and Revelations which lead to questions about the nature of motherhood and the inadequacy of colourblindness. Honestly overall I very much sympathize with [this review](https://www.theguardian.com/books/2017/nov/12/little-fires-everywhere-celeste-ng-review) ; It’s well crafted, it really should work, I couldn’t get into it, and ironically what it’s missing is a bit of fire.

  

### Washington Black, Esi Edugyan

Following the life of Washington Black, an 11 year old slave, as he escapes a sugar plantation in Barbados aboard a ‘cloud catcher’ (hot air balloon) alongside the plantation owner’s kinder (abolitionist?) brother, travels the world, flees the slave-catcher sent to kill him, and develops as an artist and a marine scientist. I tend to find the first-person past-tense narration of someone’s experiences years ago as a child to be slightly irritating, as it lends a sort of preternatural wisdom to the child and superhuman memory to the adult, but it’s still a well written novel and I enjoyed it.

  

## Plays

{{% marginnote %}} All these plays were performed via Zoom with my play-reading group.{{% /marginnote %}} 

### The Real Inspector Hound, Tom Stoppard

There’s a play. Within the play there is a play. Within the play within the play is the first play. There is a fair amount of self-indulgent criticism of self-indulgent critics.

  

### The Seagull, Anton Chekhov

A comedy in which the punchline is “and then he killed himself!” Is therefore more Russian than Russia. The seagull dies, too.

### An Ideal Husband, Oscar Wilde

Wilde taking on a serious-ish political drama whilst still being Wilde; the result of which was accurately described by John as ‘a bit Ibsen, like A Dolls House but with knob jokes’.

  

## Nonfiction

  

### No Drama Discipline, Daniel J. Siegel, MD and Tina Pagne Bryson, Ph.D.

Begun last month and finished this month. Largely this just confirms parenting instincts that I already have, but there are some interesting points. In particular I liked the metaphor of helping your child (especially when they are distressed) to navigate a canoe on a river between two banks, with ‘chaos’ on the one side and ‘rigidity’ on the other. This struck me as both true to my experience of parenting and as having an interesting parallel to Sartre’s concept of living in ‘good faith’. They also draw attention to the tendency of adults to dismiss children’s lived experiences, which again is interesting to me as a philosopher as well as a parent.

  

### Why I’m No Longer Talking to White People about Race, Reni Eddo-Lodge

Read for Philsoc. Shaun warned us all to brace ourselves for the interview with Nick Griffin in Chapter Four, but there is no such thing as being sufficiently braced for Nick Griffin. I experienced this book as a combination of stuff that I already knew but had not seen presented together in such density, a bit of stuff I didn’t know, and (most insidiously) stuff I half-knew but hadn’t actually entered my consciousness properly, such as the fact that the Black Panthers ran a breakfast programme for children. The last category is the best reason to recommend this book.

  

### Finding Our Sea Legs, Will Buckingham

Recommended by [David](https://notebook.drmaciver.com/), which is generally a good start, but alas as a houseboater this one was always going to be a challenge. Right from the preface I spotted the game of ‘how many [boat metaphors](/2020/05/03/houseboats-as-liminal-spaces/) can I fit into a paragraph?’ By the end of the first page the book had 'cast off from its moorings' thanks to the 'navigational skill' of the publishers, the author expressing hope that it's 'seaworthy' or 'at least might not sink the moment it left port'. As it 'listed to the horizon' he realized that it 'didn't look much like the sleek philosophical craft that plied the waters of academic philosophy' having none of their 'clean aerodynamic lines' and the entire thing had got on my last nerve. I did persist with it for a bit but the boat metaphor density did not decrease sufficiently for me not to be entirely distracted from the broader point of the book. I’m terribly sorry, David, I’m sure it’s objectively very good.

  

(And I do actually like the central idea of learning ethics through stories, so I may have another go at this one next month, we’ll see.)