---
title: Painting and Procrastination
author: "Lisa McNulty"  
date: "2020-07-26"  
series:  
tags:
  - "Houseboats"
  - "Procrastination"
refs:  
twitterImg: brush.jpg
description: "Imagine that this is a metaphor for work in general"

---


Houseboats need paint. They need quite a lot of paint, quite often. I got some advice when I first bought the boat: figure out how much you can get done in an hour, or half an hour, including setting up your equipment and cleaning it and putting it away. Do this because you will often have an hour to paint, but you will far less often have a day to do it. 

I have entirely failed to take this advice for a couple of reasons. 

Firstly, setting up for painting is time consuming. You need to find clothes that you don’t mind ruining, some sheeting or something to cover up anything nearby that you don’t want to get paint on. You have to locate the right paint (primer, undercoat, enamel topcoat), brushes, white spirit, cleaning rags, and paint kettles. Afterwards you need to get the paint off your hands, your brushes, and the nearby things that you managed to get paint splashes on anyway, tidy and put everything away, and (if it’s exterior painting, which it probably shall be) hope against hope that it doesn’t rain and ruin your work before everything dries off. This feels like a tremendous palaver to go through for a mere hour’s worth of painting.

(All this is after you have already cleaned the surface, quite possibly sanded it, cleaned it again, applied Fertan to any rust spots, left it a day to do its work, and then brushed away the powdery black dust that the Fertan produces. All this before you can think about the two coats each of primer, undercoat, and top coat). 

Secondly, most of the surfaces are very large and don’t split off into obvious sections. If you artificially divide it into sections in order to spend only an hour or so on painting each time, then there is a very clear line between the area that has been painted and the areas that haven’t. It draws attention to all the things that haven’t yet been done. If you feel the need to be rewarded by your effort by a Lovely Shiny Thing (and I do), then this is something of a downer. 

For these reasons it is very tempting to spend a chunk of time Painting All The Things, collapse into a heap, and then not do it again for ages. This results in an overwhelming amount of work to do whenever you actually do it, and quite possibly in giving up and paying someone else to do it, which is devastatingly and pointlessly expensive. 

All this feels like it is building up as a metaphor for work in general, or for self-improvement in particular. Imagine I did that and make it super-pertinent to you. Reply to me on Twitter and I’ll gleefully take credit.  But manual work isn’t a metaphor for intellectual work, it _is_ intellectual work, as anyone who has taken on (say) a major renovation project knows. So I’ll solve my problem, and if you can borrow from that solution and apply it to something else, more power to you. 

Here’s what’s necessary: 



*   Schedule regular times to paint. 
*   Gather everything together that is needed for the project in one place, perhaps in a box, in an accessible place, to absolutely minimise set-up time. 
*   Take the original advice and literally time myself painting for an hour. Get used to that being a ‘unit of success.’ 
*   It’s not going to look complete afterwards, because it isn’t complete, and it never really will be. It’s a bloody great big houseboat, you basically chose to live on the Forth Bridge, you idiot. Get accustomed to that. 
*   Identify the sticking points and research ways to get better at them, in particular: learn to clean brushes properly so they don’t get ruined so quickly (it’s harder than it sounds), minimising the paint/white spirit that gets on my eczema-prone hands (work gloves are too awkward but I haven’t tried latex gloves, and that might work. 

Feel free to abstract some wisdom from this experience. Meanwhile, I need a tea break. 
