---
title: "May Reading"
author: "Lisa McNulty"
date: "2020-05-31"
series:
- "Reading"
categories: 
  - "Self Improvement"
tags: 
refs:
- "Jordy Rosenburg"
- "Jeanette Winterson"
- "Michael Moorcock"
- "Oscar Wilde"
- "Tom Stoppard"
- "Rachel Hoffman"
- "Daniel J. Siegel"
- "Tina Pagne Bryson"

---

My plan is for the last entry of every month to be a record of the reading I’ve done that month. I’m not going to attempt anything significant in terms of reviews unless the mood takes me, but I’ll include at least a line or two of description.This is what I’ve read in May: 

## Novels

### Confessions of the Fox, Jordy Rosenburg.
Compellingly strange, half written in footnotes, this is two novels in one. The first is about the eighteenth century thief Jack Sheppard. The  second is about R. Voth, the academic uncovering Jack’s experiences as a trans man, and sharing his own, whilst attempting to manage the world’s worst editor. This is an inadequate description. Read it. 

### Written on the Body, Jeanette Winterson. 
An old favourite revisited. The narrator is given neither name nor gender. The story centres on their love of a married woman. The whole thing is a kind of meditation on love, desire, and embodiment. 

### An Alien Heat (Dancers at the End of Time), Michael Moorcock. 
Another re-read. Depicts the hero Jherek Carnelian, resident of a far flung future as imagined by Oscar Wilde in a particularly decadent mood, and his amusing decision to fall in love with the nineteenth century lady and unwilling time-traveller Mrs Amelia Underwood.

## Plays

### The Importance of Being Earnest, Oscar Wilde.  
Actual Wilde, this time. This was performed over Zoom with my playreading group. I got to reprise the role of Lady Bracknell for the first act, which was a joy. 

### Arcadia, Tom Stoppard.  
Another one from the playreading group. This is the only play I've ever heard of which has a detailed description of an iterated algorithm as a key plot point. Also someone gets fucked in a gazebo but frankly that's an afterthought by comparison.

## Nonfiction

### Unfuck your Habitat, Rachel Hoffman. 
I have taken virtually none of the advice in this book in any direct way and yet it has somehow got me in the headspace for cleaning and organising, so I’ll call that an overall success.  

### No Drama Discipline, Daniel J. Siegel, MD and Tina Pagne Bryson, Ph.D. 
I’m only about a third into this one and so far it’s essentially telling me that I’m doing parenting right already. Which is gratifying but not necessarily useful. 


I have begun Introduction to Philosophical Logic by A. C. Grayling, but I got cross with it from [the preface alone.](/2020/05/26/the-great-shallows-of-philosophy/). We’ll see if it makes it into next month’s list.  

