---
title:  ‘Urgh’ Fields and ‘Argh’ Fields
author: "Lisa McNulty"  
date: "2020-08-02"  
series:  
tags:
refs:  
- "Arthur Conan Doyle"
- "Dylan Moran"
- "Brendan Mahan"
twitterImg: bedstead.jpg
description: "Maybe there are no flamingoes serving drinks."

---





My online course [‘How Not To Think Like Sherlock Holmes’](/page/sherlock/) has finally started. This is based on an idea that I had years ago, that I’ve invested quite a lot in, in bits and pieces over time, and the fact that it’s finally underway feels like kind of a big deal. The strange thing is that it _shouldn’t_ be a big deal. Teaching an online class of this kind is well within my abilities. But it’s been ‘in development’ (albeit mostly not actively) for so long, that it grew within my own mind into something disproportionately difficult and significant. The result is that I could have got the course up and running several months ago, but it took til now for me to do so, because I didn’t want to do it till I could do it _right_. Objectively, however, I could have done it perfectly well back in late May or early June, and waiting until after my university marking was (largely) finished was overkill. Actually, I’m pretty sure I was kind of aware of that at the time. So what happened?

Essentially it developed a severe ‘argh’ field. This is a cousin to the [‘urgh’ field,](https://www.lesswrong.com/posts/EFQ3F6kmt4WHXRqik/ugh-fields) but I think it is phenomenologically distinct. 

{{% marginnote %}}  A useful related concept is the [‘Wall of Awful’](https://www.youtube.com/watch?v=Uo08uS904Rg)  
   {{% /marginnote %}}

The archetypal ‘urgh’ field may arise when a project is actually unpleasant and therefore aversive to begin with, resulting in procrastination, which then increases your aversion as the unpleasant task becomes more and more urgent. This is the ‘my tax returns are almost overdue and I shall ignore this fact as long as possible’ kind of phenomenon.

But it is also very possible to develop aversion fields around projects you actually love. These are the ones with the most potential, the ones that you can see going somewhere interesting. The aversion to working on these develops because you very much do not want to be proved wrong. The aversion is just as real, but very much more ‘argh’ than ‘urgh’. 

Dylan Moran says it best: 

```{r, eval=TRUE, echo=FALSE}
blogdown::shortcode("youtube", "NU8C88UczmU?t=35")
```


>Release your potential! That’s another one. Now that’s a very, very dangerous idea. You should stay away from your potential, I mean that is something you should leave absolutely alone. Don’t - you’ll mess it up! It’s potential - leave it!’ 

Maybe no one else will like this idea. Maybe it’s too basic, and I’m going over obvious things. Maybe it’s too specific and self-indulgent.  Maybe there are no flamingoes serving drinks. Maybe you have to listen to the clip so that line doesn't seem like a complete non-sequitur. 

Point is: the longer the distance between having the idea and implementing the idea, the more attached to the idea you may become, and the more aversive it may be to actually try it, in case it doesn’t work. The more research and double-checks and dry runs you will want to do before actually dipping your toe in the water. By contrast, when the thought occurred that I might create a similar online course based on [philosophy and Doctor Who](/2020/05/05/immortality-and-change-in-doctor-who/), I said that I could pretty much start whenever. It’s not an easier project, I’ve just had less time to worry about it. 

I’m hoping that actually getting this project done at last will inspire me to take on a project that has been in the background even longer; namely harvesting another academic paper or two from my long-ago Ph.D.  Mostly, though, I just want to ensure that I don’t let potentially good ideas sleep so long in future. 




