---
title: "The Veil of Ignorance"
author: "Lisa McNulty"  
date: "2020-05-19"  
series:  
- "Philsoc"
tags:
refs:
 - "John Rawls"
 - "Robert Nozick"
 - "John Locke"
---




It’s a Philosophy Society day today, and we are going to be talking about justice and fairness. I’ve sent round some readings from Rawls and Nozick, and I’ll use this writing session as a bit of a refresher. I’m just gonna focus on Rawls though.

Rawls is inspired by Locke, in the sense that he finds his idea of ‘natural’ or ‘basic’ and ‘inalienable’ rights attractive and wants to retain that concept. However, he recognises the pesky fact that a pre-social ‘state of nature’ never actually existed, and he isn’t willing to bring God into it. So, I mean, not that Lockean for a Lockean.

The thing is, in Locke, the idea of basic and inalienable rights just comes from the idea of human beings in the state of nature granted rights by God. Basically, we leave the state of nature and enter into a social contract specifically in order to protect our natural rights, not in order to give them up. The Lockean idea is that the government doesn’t give you rights, rather, you entrust the protection of your existing, God-given rights to the government. Therefore a government which threatens our basic rights to ‘Life, Liberty and Property’{{% marginnote %}}Why the Americans shifted this to ‘pursuit of happiness’ is a bit of a mystery. Why did you make it less capitalist, America? It’s not like you. {{% /marginnote %}} is by definition an illegitimate government which ought to be overthrown.

If you are cutting out both the ‘state of nature’ and the ‘God’ part of natural rights theory, then you have to come up with a new starting point to justify the whole ‘inalienable rights’ idea. Rawl’s answer to this is to think of the social contract not as a historical event but as a hypothetical event, a thought experiment.

In ‘A Theory of Justice’, Rawls concerns himself with distributive justice: with who gets what. He’s not only concerned with economic distribution, although that is definitely part of the equation. He’s also concerned with status, power, and freedoms: anything which brings benefit to human life and might be distributed evenly or unevenly. He wants to establish principles which we can use to decide how such goods are divided.

So we have to agree on a set of principles. The trouble is, which principles we would agree to depends on our starting position. The wealthy might not agree to any social contract which took their wealth away from them. On the other hand, Rawls considers the possibility that the enslaved might agree to a contract which offered them better treatment than they were currently experiencing, even if it kept them slaves.

Rawls solution to this is the ‘veil of ignorance’.

The veil of ignorance is a bit of a misnomer. In this imaginary scenario, you aren’t ignorant about the way the world is, and in fact you know a good deal about politics and economics and the world in general: enough to design a whole new world order.

What you are ignorant about is yourself.

You don’t know your position in society, or the position you will occupy in the society you are building. You don’t know if you are successful or unsuccessful, rich or poor, how much power and status you have, what your special talents are (how intelligent you are, how physically strong). You don’t know your particular moral or religious beliefs, your gender or sexual orientation, your tastes.... You name it, you don’t know it about you.

And in this state of not knowing about you, you are meant to choose the principles of society in a ‘mutually disinterested’ way. In short, you are not choosing for the sake of anyone else’s wellbeing but for your own.

The philosophical trick here is that if you are choosing selfishly but know nothing about yourself you will choose a society where your life will be reasonably good no matter where you end up. This rules out a sexist, racist, intolerant society, and any society in which the wealthy are left untaxed{{% marginnote %}}Rawls doesn’t rule out inequalities of income where those inequalities are ‘to the benefit of all’: for example we might want medicine to be a lucrative and thus competitive profession. But this is only justifiable if everyone gets the opportunity to study medicine if they so choose. {{% /marginnote %}} whilst the poor live in inhumane conditions. In short, if you don’t know whether you will end up oppressed, you will ensure that no one is being oppressed. Rawls calls this ‘justice as fairness’.

This is neat, tidy, and wrong.

It is considered uncouth to point out that thought experiments describe situations which could never happen for practical reasons. Rawls knew perfectly well that we couldn’t actually enter the veil of ignorance, but still believed that we could arrive at certain principles by imagining ourselves there. I therefore want to make it clear that I am not objecting to the fact that the Veil is imaginary, I am objecting to what is being imagined.

In a previous post I spoke about there being different kinds of knowledge: propositional knowledge, know-how, and knowledge by acquaintance (familiarity). One version of knowledge by acquaintance (or possibly it’s cousin) is standpoint knowledge.

Standpoint knowledge is roughly ‘knowing what it is like to be [something, someone]’. In feminist epistemology, the term is used in order to express the idea that first person experience of oppression is a special kind of knowledge, which cannot be passed on via testimony to those who have not experienced oppression (or have not experienced oppression of that particular kind). We may have propositional knowledge about oppression without having experienced it: we can know facts about it. We can even have knowledge by acquaintance, in the sense that we might be close to someone else or to a whole community who experience a particular kind of oppression which we have not ourselves experienced. But unless we have experienced a particular kind of oppression for ourselves, we do not have the necessary standpoint knowledge to know what it is like, and our epistemic and moral duty is to listen to those who have when forming policies or shaping practices intended to mitigate oppression.

Because we don’t know how to fix it if we don’t know what it’s like.

The Veil of Ignorance as Rawls conceives of it makes this moral and epistemic duty impossible. Effectively we are imagining a scenario in which the only knowledge available is propositional knowledge: no one knows what it is like to be anyone, they just know a bunch of facts. This means that Rawls is aiming to create a society which doesn’t oppress people, by gathering a bunch of people in a room who have forgotten what it is like to be oppressed if they ever knew in the first place, seeing what social contract they would agree to, and sticking to it.

The core idea of bypassing selfishness is all well and good. But the shape of the thought experiment dismisses the voices of the very people who this theoretical society is supposed to liberate. This strikes me as neither just nor fair.