---
title: "Decisions, Decisions"
author: "Lisa McNulty"
date: "2020-05-12"
series:
tags:
- "decisions"
---

There is a trope common in popular culture about making decisions. It goes like this: 

>**Girlfriend:** I’m hungry. 

>**Boyfriend:** What would you like to eat? 

>**Girlfriend:** I don’t mind, you choose. 

>**Boyfriend:** Mexican? 

>**Girlfriend:** No, not Mexican, actually. I’m not in the mood for anything spicy. 

>**Boyfriend:** Pizza, then? 

>**Girlfriend:** Mmm, maybe not? 

{{% marginnote %}}This particular dynamic is super-gendered in the popular imagination so I’ve left that in place here, although I’m uncertain how gendered it *actually* is. Certainly I think the experience of decision fatigue is a universal one, and difficulty explaining what’s going on is pretty common. {{% /marginnote %}}
... and so on until there is a fight. You know how this goes. 

Essentially, making decisions, even minor decisions, is a form of emotional labour. If you are tired, the labour is more difficult than usual. (If you are tired and hungry, even more so). This doesn’t mean you don’t have preferences, it means that your brain is not very good at accessing what those preferences are right now, and so you need assistance in figuring out what they are. 

There is a hermeneutical issue going on here, in that this is a fairly universal experience, but people have difficulty in communicating the nature of that experience. Being the person who gets to make the decisions tends by default to be considered a position of power and privilege. In this instance, it isn’t; you are simply doing a favour for someone else. But it is hard to reframe the dynamic in this way unless you have the language with which to do so. Most people aren’t familiar with the term [‘decision fatigue’](https://en.wikipedia.org/wiki/Decision_fatigue),  {{% marginnote %}} The term, ‘decision fatigue’ doesn’t entirely work anyway, since it is intended to mean specifically ‘tired of making decisions’, whereas the more common experience is that fatigue or stress of any kind can result in decision making becoming more difficult.  {{% /marginnote %}}and so it is hard to articulate that ‘I don’t mind, you choose’ is asking a favour rather than granting one. This creates two kinds of communication problems. The first is the immediate problem of communicating with other people who are actually in the situation with you (as above). The second is the longer-term problem that it prevents us from pooling resources with others who have similar experiences and figuring out solutions for it. 

There are in fact some good solutions out there, exemplified in [this thread.](https://ask.metafilter.com/340682/Decision-Making-Frameworks-Hacks-for-Couples). This is aimed at couples but mostly could be adapted for larger groups. One technique suggested is a rule that when selecting where to go for dinner, you can't veto the current choice without suggesting a new option. This would, I think, be a useful default to ensure that the emotional labour is equitably split most of the time. However it would not help with the particular situation in which one person is temporarily unable to deal with decision making. In this case, perhaps the simplest solution presented is for Person A to offer three options for Person B to choose between. The Person A is clearly doing the emotional labour, but by not choosing unilaterally, they are also acknowledging the fact that the Person B still has preferences, they just don't know what they are right now. Another advantage of this system is that it places reasonable limits on the emotional labour done by Person A. They are not expected to keep listing options until one stands out as the ideal one to Person B. This minimizes the frustration involved in the role and therefore makes it more feasible as a long term solution; provided of course that Person B steps up when the tide turns. 