---
title: "The Great Shallows of Philosophy"
author: "Lisa McNulty"
date: "2020-05-26"
tags: 
refs:
   - "A.C. Grayling"
---



I have a comfort zone in philosophy: epistemology and ethics. Within those, I like my questions pretty applied. I like questions about the nature of knowledge; but I immediately want to relate them to questions about good and bad ways of pursuing knowledge (philosophy of science and social science) or disseminating it (philosophy of education, social epistemology). I am interested in ethics, but I prefer applied ethics, where you are trying to solve particular ethical problems and bring in different ethical systems as tools to do it, to ‘straight’ ethics, which involves studying the systems themselves in great depth - especially as the subtext of such study is often ‘choose between these,’ and [consistency is the enemy](/2020/05/04/consistency-is-the-enemy/). Even with applied ethics, I want a bit of empirical data if possible. I like to co-author with educationalists, who tend to bring data to the table and appreciate a philosophical framework to arrange it in. [Metaethics](https://en.wikipedia.org/wiki/Meta-ethics) leaves me cold.

I also like a bit of logic, but informal logic: I like tools to describe and analyse what philosophers call ‘ordinary language arguments’, with the goal of improving practical reasoning skills. I’m not really into the more formal, mathematical-ish forms of logic. Also it has been a looooong time since I read any real metaphysics.

Comfort zones are for expanding out of, however, so I’ve got myself a general introduction to Philosophical Logic and another to Metaphysics to see how it goes.

I’ve started with An Introduction to Philosophical Logic by A. C. Grayling. The first paragraph of the preface is as follows:

> “Philosophers are fond of pointing out that there is no shallow-end in
> philosophy. This is true. Philosophy is a subject which is often
> complex and sometimes difficult. Books which purvey shallow-end
> philosophy are at risk of purveying shallow philosophy instead, and
> accordingly distort and falsify its problems. Because philosophy is
> among other things, ‘the dogged struggle to achieve clarity’ as
> William James puts it, shallow-end treatments of philosophy’s problems
> are therefore not merely useless but counterproductive. So I have not
> tried, in this book, to pretend that the questions it deals with are
> simple. They are challenging, and demand careful study. 
> 
> All this said, and philosophy’s deep-endedness acknowledged, it remains that new
> swimmers must, somehow, be helped into the flood. There are various
> ways of introducing philosophy, but the best of them is the tutorial.
> In comparison with a tutorial’s potential for heated dialogue, printed
> pages offer cold monologues merely. Still, books have important uses;
> one can mull over them, linger on this or that point, pencil insights
> and objurgations in the margins: scriptae manent, verbena volant after
> all.

  

Oh, the ways in which I hate this.

The intended audience is one which will see no tension whatsoever between praising ‘the dogged struggle to achieve clarity’ and immediately quoting in Latin.

(Or worse, will not admit to seeing tension, for fear of seeming stupid).

{{% marginnote %}} I did not know that Latin phrase or its origin. I could piece together a vague meaning from plausible etymology and from context. I looked it up online to get a precise meaning, ([spoken words fly away, written words remain](https://en.wikipedia.org/wiki/Verba_volant,_scripta_manent)) which was not an option when this was written in 1982. {{% /marginnote %}}

Of course philosophy is complex and sometimes difficult. The same is true of mathematics, of literary criticism, of science, of history. Yet none of those subjects goes about claiming that there is ‘no shallow end’, no simple and comprehensible beginning to the problems which get deeper and more difficult the further in you go. If they did, the primary school curriculum would be much depleted.

The message, loud and clear, is that philosophy is for philosophers. It is only for those who will plunge into the flood, preferably hand in hand with an expensive personal tutor. {{% marginnote %}} One-to-one tutorials can only provide ‘heated dialogue’ if the student regards themselves as an expert tutor’s intellectual equal. Most won’t. Some do in a way they shouldn’t. Otherwise, dialogue is best achieved with a group of students discussing ideas with each other, and the seminar leader acting as a facilitator. Even then, I would consider a ‘heated’ dialogue to be a failure mode, not a goal. {{% /marginnote %}}

That means it is not for the very young, not for the amateur, not for those who would dip in, take what they need, and use it for their own purposes. It’s probably not for you.

We have immediate neighbours in Europe who treat philosophy as a normal and integrated part of the school curriculum. They don’t have a clear distinction between ‘pop philosophy’ and ‘academic philosophy’ with writers of the second kind gleefully mocking and distancing themselves from the writers of the first. There are British philosophers who are working hard on these cultural issues, but the shift has been painfully slow.

At present, I teach philosophy in two contexts. The first is philosophy for children. Today I taught a Zoom class to a group of nine-year-olds in which we related John Locke’s concept of the Happy Prisoner to their experiences of lockdown.

The second is in an education department. One of the courses I’ve taught is euphemistically titled ‘Aims in Education’. As far as I can tell, the only reason it isn’t titled ‘Philosophy of Education’ is that our student cohort (the vast majority of whom are women, non-white, and the first in their families to attend university) would be immediately convinced that the course was Not For Them.

Because there is ‘no shallow end in philosophy’.

Fuck that.

Of course there is. And if the authors you have read have not the skill to guide you to where it is, that is their failing. The water is there, and it is yours as much as anyone’s.

Come, swim.