---  
title: "Being an Expert Novice"  
author: "Lisa McNulty"  
date: "2020-05-16"  
series:  
tags:
- "Hobbies"
- "Gilbert and Sullivan"
- "Expertise"
refs:
- "John Locke"
---



Parenthood sucks for hobbies. The first few years of a child’s life are overwhelming in the focus that they demand from you. It’s very easy to lose things, small and significant, which are part of who you are. So a few months ago, I began something of a reclamation project. This was a conscious effort to reclaim things that used to bring me joy and which I had somewhat abandoned. Part of this was re-reading favourite books, buying the good tea, and other small things of that nature. The most significant thing, though, was to join a Gilbert and Sullivan Society.

I have an odd relationship with music. I can sing, but I can’t play an instrument. (Well, not really. I can strum a couple of things on the guitar). The result of not learning an instrument is that I can't really read music: if I know a piece really well, then I can recognise how the written music connects to it, but I can’t sight-read at all.

Normally when people say ‘I can sing but I can’t play an instrument’, it translates to ‘I can keep more or less in tune’. That’s not what I mean. I sing weirdly well for someone who can’t sight-read. I’ve had operatic singing lessons to Grade Six level, I’ve sung in choirs in the Royal Albert Hall and in Canterbury Cathedral, I can take on fairly challenging pieces with relative ease. But I can’t read music. I listen to recorded music and learn that way.

I’d never sung Gilbert and Sullivan before. But it’s odd that I hadn’t. I befriended a number of people at a university I was expecting to attend for my Ph.D., who happened to be in the university’s G&S society. I signed up for the society’s email list, which included a great deal of general friendly banter, and fell in quite well with the group whilst I spent eight months teaching abroad. My intention was to join the society when I came back, but I ended up attending another university, which didn’t have a G&S society. I still have friends from that email list and they easily forget that I never sang with them. Given the number of times I’ve seen G&S productions with friends performing in them, or watched G&S on DVD, it’s easy for me to forget this, too. Last November was my first G&S show, and it feels very strange that this is the case. I more-or-less know a lot of G&S songs; I’ve just not actually performed them.

I very much enjoy the society, but I have considered leaving it more than once. This is in part because of the disconcerting feeling of being both expert and novice at the same time.

I could have joined them and said ‘I’ve never done G&S before and I can’t sight-read’. If I’d done this, I would have been treated a particular way which would not have lined up with my abilities. Or, I could have said ‘I have Grade Six in operatic singing and I’ve sung in Canterbury Cathedral’. In this case I would have been treated in a very different way... which also would not have lined up with my abilities. I could have undersold myself, or oversold myself. But selling myself accurately didn’t seem to be an option.

As it was, I didn’t sell myself at all. I simply turned up and quietly took a position in the chorus and did the best I could. I kind of avoided conversations about my ability level. I learnt the chorus parts and sung them pretty well, with minimal practice (I joined part-way through rehearsals). It was fun, and I did fine.

The question is what happens next.

I am more than capable of singing a lead role, in terms of my actual vocal ability. However, it would be far harder to hack around an inability to sight read if I take on a lead role, just because there would be so much more material to learn, and no opportunity to just follow other people’s voices if I’m uncertain. Therefore, I would have to learn something embarrassingly basic and foundational in order to advance to a position that I know I am otherwise capable of taking on.

I find myself in a similar situation professionally.

I have a Ph.D., I have publications, I’ve taught at university level on and off since I was working on my Masters degree in 2006, I have a Fellowship of the Higher Education Academy. But I went from my Ph.D. straight to a teaching-only position at a small private American-style university in London. It was literally the first interview I had, and almost the first job I applied for. I was teaching on a Liberal Arts degree rather than a Philosophy degree, so my courses were all at an introductory level. The university didn’t particularly encourage research, and so after the first year (when I was still finishing my thesis) I took a rather leisurely approach to it. Then I had a baby, and research dropped off the radar altogether. When my daughter was three years old, I was made redundant. I did not have the geographical flexibility to apply for jobs all over the country, and I needed to continue working only part-time, so I retrained with the Philosophy Foundation to teach philosophy to children. Eventually I was offered VL work in an Education Department, on the strength of my position there as a research associate in the Philosophy of Education Research Centre.

So, I’ve done a massive amount of university teaching! but almost none of it in an education department, or indeed in the British system. I’ve taught philosophy in schools and I am a school governor, the Vice Chair of the Education Committee! but I don’t have Qualified Teacher Status, which excludes me from a lot of education jobs. I’m a very capable writer! with a very short publication list. I am lecturing in one of the best education departments in the country! as a Visiting Lecturer, and therefore with no job security and no clear path of advancement.

Again, I feel like I have a choice of over-selling myself or under-selling myself. My automatic focus is to ensure that I don’t sell my students short, so I have spent a good deal of time seeking advice from my colleagues to ensure that I know the particular materials of the courses and the procedures of the institution. They have at points naturally slipped into treating me as one would a fresh postgraduate, who (for example) doesn’t know how to mark papers, rather than doesn’t know how to mark education papers. This is unfair. However if they treated me exactly as one would a full lecturer... that would also be unfair.

What to do, then? If I deny my status as a novice, then I will do my job badly. If I deny my status as an expert, I will not be taken seriously enough to advance to better things.

In both cases, I need:

-   to fearlessly present myself as both novice and expert. For this reason I’ve put in a request for a mentor at my university, who will hopefully be able to get a complete picture of what I can and cannot do, and help me to form a plan for improvement and advancement. (With my G&S society, it might be as simple as letting a senior member know and asking for advice on learning how to sight-read.)
    

  

-   to practice self-forgiveness. I could have learnt sight-reading when I first had singing lessons. I could have found a G&S society when I first moved to London and been in half a dozen shows by now. I didn’t do these things. I could have published more straight out of my Ph.D., or moved into an education specialism earlier, or taken any number of decisions which might have left me in a stronger professional position at this stage. I didn’t do these things. Self-recrimination would lead me to deny my position as an expert altogether. Instead, I have to unapologetically start from where I am.