---
title: "Drabble - Aristotle’s Ethics"
author: "Lisa McNulty"
date: "2020-05-23"
series:
  - "Drabble"
tags: 
    - "ethics"
refs:
   - "Aristotle"
---


For the uninitiated, a ‘drabble’ is a work of fiction of exactly 100 words long, which is intended to test the writer’s ability to express interesting ideas in a confined space. I am experimenting here with using the format to explain philosophical concepts. This may become something I use as writing prompts for days when I am short of time and spoons.

(This isn’t the drabble yet. The next paragraph is the drabble. All will become clear.)

Aristotle’s ethics focuses on virtues, rather than actions (deontology) or consequences (utilitarianism). Virtues lead to eudaimonia: happiness, or more precisely ‘thriving’. They are acquired through habituation from childhood. Since virtues are required for happiness, we theoretically all want to be virtuous, but can fail to be virtuous owing to akrasia (weakness of will). Cardinal virtues include prudence, temperance, courage, and justice. Rather than being the opposite of a vice, Aristotelian virtues lie between excess and deficiency. In the case of courage, the ‘excess’ state would be foolhardiness, and ‘deficient’ state cowardice, with courage as the ‘golden mean’ between these extremes.