---
title: "Houseboats as liminal spaces"
author: "Lisa McNulty"
date: "2020-05-03"
output:
  tufte::tufte_html: default
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```


I like to joke that houseboats ruin all metaphors. Examples include:

* Are you on board? No, but I'll be home in a bit.

* Let's push the boat out! But we'd need to get longer standoffs and it would take all afternoon, can we not?

* Wouldn't touch you with a six foot barge pole! Well, good, it's all covered in river goop.

* I'll show you the ropes! There are the ropes.

Seriously, there are a lot of boat metaphors. To explain and thus ruin the joke:  Houseboats mess with the metaphors because the experiences those metaphors describe are literal and everyday ones for the people who live on them, but unfamiliar to those who don’t. 

It’s not, however, merely that boats are unfamiliar. They are what we might call the ‘familiar unfamiliar’ to most people: that is, they have experience of them, but that experience is in a particular limited context which leads them to bring certain assumptions with them as to what a boat is and is not for, and thus what counts as appropriate behaviour around them. Intellectually, people do realise that boats can be homes, but many people still don’t grok the idea. A prime example of this occurred yesterday when a passing walker came on board to have a bit of a sit down on the benches on-deck, until he was scared off by my husband appearing through the hatch. 

This was fairly extreme, but the perception that boats are public spaces in a way that houses are not is pervasive in a number of other ways. It is not uncommon for people to stop next to the boat and stare over it into the middle distance. This is entirely normal ‘walking by a river’ behaviour. It’s also kind of unnerving to see from inside the boat. (Why have you stopped next to my gate? Do I know you? Are you delivering something? Or, you are staring into the middle distance. Fair enough, carry on.) It’s also not uncommon for people I’ve never met to start talking to me when I’m on deck, asking what it’s like to live on a boat, and (gasp at the unEnglishness of it all ) ask me how much it costs. In terms of my experience of events, this is the exact same as if someone had stopped me in my front garden to ask about my mortgage; which the selfsame people would never dream of doing. 

The belief that boats are somehow public spaces is connected to the fact that they are liminal spaces. They exist in the in-between. They are not quite boats, and not quite houses. They are moored at the river’s edge; between land and water. They (can) stay in the same location, but they are in principle portable; they are after all built to go from place to place. Usually houseboats are antiques, but renovated to become homes, so they are also in a sense new-builds. Houseboaters are generally welcomed by landlubbing society so long as we make an attractive view; but we are distinct from it. Whilst technically we live in Brentford, it is truer to say that we live in the Thames, which is a community of its own. Houseboating is attractive (I’ve always wanted to live on a boat!) but alienating (but I’d never dare). 

It wouldn’t exactly be true to say that houseboats attract rebels. Boaters aren’t outcasts from society, we aren’t in a cult. (Quite). But we nonetheless find ourselves breaking, and causing others to break, quite a lot of social rules that no-one was really aware existed *until* they were broken. It’s a gentle kind of liberation. 
