---  
title: "Helen Longino on Cognitively Optimal Communities"
author: "Lisa McNulty"  
date: "2020-05-17"  
series:  
tags:
- "soup"
refs:
  "Helen Longino"
---



Helen Longino is a social epistemologist and a philosopher of science, interested in establishing what it takes for the consensus of a research group to count as knowledge. According to Longino, knowledge ‘is constructed not by individuals, but by an interactive dialogic community’ (Longino 1994: 143). In short, knowledge arises from dialogue, but not just any form of dialogue. The interactions between members of a cognitive community must amount to ‘genuine and mutual checks’ if the group’s enquiries are to be objective.

Longino identifies four characteristics which are necessary to enable such checks. For the consensus of a community to count as knowledge:

1.  There must be publicly recognized forums for the criticism of evidence, of methods, of assumptions and reasoning.
    

  

2.  There must be an uptake of criticism. The community must not merely tolerate dissent; its beliefs and theories must change over time in response to the critical discourse taking place within it.
    

  

3.  There must be publicly recognized standards by reference to which theories, hypotheses, and observational practices are evaluated and by appeal to which criticism is made relevant to the goals of the inquiring community…
    

  

4.  Finally, communities must be characterized by equality of intellectual authority. What consensus exists must be the result not of exercise of political or economic power, or of the exclusion of dissenting perspectives, but as a result of critical dialogue in which all relevant perspectives are represented. This criterion is meant to impose duties of inclusion: it does not require that each individual, no matter what her or his past record or state of training, should be granted equal authority on every matter (Longino 1994: 145).
    

Requirement (1) asks that the evidence, methods, assumptions, and lines of reasoning used must be put up for public scrutiny. ‘Public’ might in some cases mean the newspaper-reading public (for example in the reasoning used to justify political decisions in a democracy), but for more specialist areas of knowledge it would involve, for example, conferences and peer-reviewed journals, or less formally, the scrutiny of one’s colleagues.

Requirement (2) asks that where there is criticism, it must be responded to. A cognitively healthy group will change in response to the critical discourse taking place within it, meaning that well-placed criticisms should result in a change of belief or practice. Of course, not all criticisms will be well-placed. In the case of ill-informed criticisms the response can be brief, but there must nonetheless be a response justifying one’s position, as this avoids complacency. The skill of distinguishing a good criticism from an ill-informed one is best regarded as part of our education in the field in question: it is Green’s ‘conscience of craft’. But even if we lack expertise in the field in question, we can still assume that a group which never adapts as a result of criticism is probably ignoring some well-placed criticisms.

Requirement (3) refines requirement (1) by asking that the group has a set of standards ‘by reference to which theories, hypotheses, and observational practices are evaluated’. By adhering to such standards, individuals and groups show themselves to be open to criticism. They offer a clear message: ‘Here are our standards. When we fail to reach these standards, which we have agreed to strive for, then our work is inadequate’. This is, I would argue, rather complicated by the fact that cognitive groups do not necessarily agree as to what standards they should be working to; as the controversy in archaeological theory over the past few decades shows. In such a case, the standards themselves are questioned and criticised. However I don’t think this affects Longino’s key point, which is that a cognitive community which has no publicly accessible set of epistemic standards at all fails to be objective.

Requirement (4), the requirement for equality of intellectual authority, needs careful explanation. Longino is not claiming anything so crude as ‘all opinions are equal’, and she is not altogether denying that being an established, experienced old hand in a field is a legitimate source of cognitive authority. But, firstly, consensus within a cognitive group should not be as a result of political factors, and secondly, it must not be the result of the exclusion of dissenting perspectives. It is worth noting that it doesn’t take a deliberate attempt at misinformation for political factors or the exclusion of new dissenting voices to occur. The effect is likely to be subtle: for example, relatively weak evidence for a politically popular conclusion may be given more weight than it deserves; and young and inexperienced researchers especially may be reluctant to properly defend any but the most compelling results, if they are contrary to the current consensus. Therefore requirement (4) is a positive requirement to encourage dissenting voices to be raised. Also, whilst experienced researchers with good reputations hopefully deserve them, their reputation should not in itself lend credence to their results.